### ISSUE TITLE
Add periodic testing to CI

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#1267]
After about 3 weeks the builds expire and our README/pypi/npm build badges go to "Never been built". I think we should do weekly builds via:

```yaml
schedules:
- cron: "0 0 * * 0"
  displayName: Weekly build on Sunday evenings
  branches:
    include:
    - main
  always: true
```

the `always` will ensure that even if no code updates, we build weekly. This is helpful for checking dependency issues earlier (e.g. #1259 ) as well as build system problems (e.g. #1253  )
