### ISSUE TITLE
treemap svg elements missing position and size making them invisible on firefox

### ISSUE THREAD

**Issue by GREEB** [finos/perspective#1983]
## Bug Report

#1327 is maybe the same bug but its closed.

### Steps to Reproduce:
Go to https://perspective.finos.org/ and toggle example to treemap
![image](https://user-images.githubusercontent.com/1221769/193642164-1091168b-62d8-4be8-bb97-51bc90b10470.png)

### Expected Result:
Open same page with `Version 104.0.5112.102 (Official Build, ungoogled-chromium) (64-bit)`
![image](https://user-images.githubusercontent.com/1221769/193642325-3ce401e7-9153-4587-b036-ab607a66a9d0.png)

### Environment:
`Firefox 105.0.1 (64-bit)`
`Windows 10`

### Additional Context:
it seems that `x: y: width: height:` do not get set in Firefox

So in Chromium the rect style is something like:
 ```css
{    
    x: 0px;
    y: 89.4314;
    width: 126.966px;
    height: 56.4545px;
    fill: rgb(71, 120, 194);
}
```

In Firefox when svg are "invisible": 
 ```css
{
   x: 0px;
   y: 0px;
   fill: rgb(36, 38, 40);
}
```
