### ISSUE TITLE
Allow for last column in spreadsheet to fill all white space

### ISSUE THREAD

**Issue by mhkeller** [finos/perspective#2381]
### Description of Problem:

I'd like to have the last column in the datagrid to extend all the way to the right for aesthetic purposes / keeping a consistent table style between applications.

### Potential Solutions:

Probably the easiest solution would be for perspective to add a class or data-attribute to the last `<td>` in the datagrid such as `.last-column` or `data-last-column="true"`.

That way, a user could add the following custom CSS to create the desired layout.

```css
perspective-viewer table tbody td {
  white-space: nowrap;
}
perspective-viewer table thead th.last-column,
perspective-viewer table tbody td.last-column {
  width: 99%;
}
```
<img width="679" alt="Screen Shot 2023-10-08 at 3 04 20 PM" src="https://github.com/finos/perspective/assets/498744/47bee872-473e-4ded-bdcc-23b78d40aa86">

This doesn't currently work using `:last-child` because the columns are loaded in a virtual table so the last `td` present in the markup may not be the last column in the actual data. 

There may be other solutions but this seems like the lightest touch and gives users a hook they can work from without affecting existing styles.

Note: I don't *think* setting the `white-space: nowrap;` breaks any existing layouts but would be worth checking.
